# Generated by Django 5.1.5 on 2025-01-24 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='name',
            new_name='company',
        ),
        migrations.AddField(
            model_name='website',
            name='source',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='token_page',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('position', models.CharField(max_length=250, null=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_addresses', to='webapp.website')),
            ],
        ),
    ]
