# Generated by Django 5.1.5 on 2025-01-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_name_website_company_website_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='emails_checked',
            field=models.BooleanField(default=False),
        ),
    ]
