# Generated by Django 5.1.5 on 2025-01-25 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_website_emails_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='updated_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
