# Generated by Django 5.1.5 on 2025-01-25 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_website_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
