# Generated by Django 5.1.5 on 2025-01-27 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_website_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_addresses', to='webapp.website'),
        ),
    ]
